### ISSUE TITLE
Feature #1: User can Navigate a search bar by entering title of entertainment to load a list from the IMDB API   

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/WatchList#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can…. Navigate a search bar by entering title of entertainment to load a list from the IMDB API   

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="205" alt="Screen Shot 2023-02-28 at 9 56 22 AM" src="https://user-images.githubusercontent.com/117954421/221939183-5e1ecc98-7d27-46af-a204-271de8b2fcbc.png">

<img width="375" alt="Screen Shot 2023-02-28 at 9 57 36 AM" src="https://user-images.githubusercontent.com/117954421/221939406-0e576520-f027-42ac-8034-9d1197e0160e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the header so that it will match the figma front page. 
- [x] Create the HTML for the main content to match the figma. 
- [x] Write CSS for model devices first
  - [x] After mobile is completed work on creating a desktop layout. 
- [x] Make the search bar input required before submitting 
- [x] Create a data object in the data.js and give it an view and entries property with an empty array
- [x] Give content on the homepage data-view="homepage" and content of results a data-view="results" 
- [x] Create a results page for the search results 
     - [x] Mobile 
     - [x] Desktop
 - [x] Returns a render function for every movie that shares that result title from the API and append it to the ul of our html 
- [x] Create a View Swap function that will let users return home from the results page 
- [x] Add a submit event listener to the form element of the search bar prevents the page from refreshing when the form is being typed in
     - [x] page should viewswap to results after the search is submitted  
- [x] create an anchor tag in the title of website that will toggle the view back to the homepage from results when clicked 

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
