### ISSUE TITLE
Feature #2: User can Click the individual movie from the results and populate the movie’s page

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/WatchList#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the individual movie from the results and create a movie page full of properties of that movie. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the "Learn More" and receive more details about the movie they wish to learn more about. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="214" alt="Screen Shot 2023-03-01 at 8 03 48 PM" src="https://user-images.githubusercontent.com/117954421/222328312-62ee78b0-c2f8-420a-b9be-bf9ee3960e53.png">

<img width="775" alt="Screen Shot 2023-03-01 at 8 05 16 PM" src="https://user-images.githubusercontent.com/117954421/222328457-40a13236-b22b-456e-8258-a445d187d935.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add another view named movieDescription
- [x] ...Create HTML layout for the new page 
     - [x] Mobile
     - [x] Desktop
- [x] Update the viewSwap function to include the new view 
- [x] Make a click event listener to the "learn more" section of the results page that viewSwaps to the movieDescription page 
- [x]  Create an add event listener that will that grabs the title, movie poster, plot/description, content rating, runtime, and critic score from the id of the movie clicked from the results page and create a new page full of more information
     - [x] Append a new DOM tree to the ul that includes the movieDescription view 

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
