### ISSUE TITLE
Feature #3: User can Able to add a movie/show from the movie page via a button/star/check to a watchlist section

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/WatchList#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a movie/show to a 'My List" page from the movie page via a button 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click a button and it will add the movie to their list 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="379" alt="Screen Shot 2023-03-03 at 10 35 29 AM" src="https://user-images.githubusercontent.com/117954421/222800565-9806c851-3ac2-4a87-a117-9d3404f0f16d.png">
<img width="387" alt="Screen Shot 2023-03-03 at 10 37 11 AM" src="https://user-images.githubusercontent.com/117954421/222800841-8b08cd4f-5d89-4f2a-9824-236a119af8e7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... Add to the LearnMoreClick function so that it creates a button element on the more info dom tree
- [x] Add css styling for the button 
     - [x] Mobile
     - [x] Desktop
- [x] Set up local storage so that when the browser refreshes the movie picked is not deleted 
- [x] Create an object after the More Info Dom Tree that holds the movie's title, img url, plot, stars, genres, Content Rating, runtime, rating 
- [x] If a movie's saved button is being clicked unshift the movie's object into the data.entries array 

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
