### ISSUE TITLE
Feature #4: User can View their list of movies 

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/WatchList#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view their list of movies that they added.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on "My List" and their movies that they added should appear. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="225" alt="Screen Shot 2023-03-03 at 4 32 43 PM" src="https://user-images.githubusercontent.com/117954421/222860759-06013974-a519-4ffb-a043-eb979abb1b9f.png">

<img width="376" alt="Screen Shot 2023-03-03 at 4 33 25 PM" src="https://user-images.githubusercontent.com/117954421/222860774-97b422e2-3916-442d-8cd7-5b1a9a8e9aa7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

Feature #4 Task 
- [x] Create another view in the ViewSwap function 
     - [x] Give the "My List" button a data-view of "my-list" 
     - [x] Create an addEventListener to the "My List" button to viewSwap
- [x] Apply CSS for the new DOM tree 
     - [x] Mobile 
     - [x] Desktop
- [x] Render a new DOM tree for the My List page based off the data.entries object's properties 
- [x] Create a for Loop through the data.entries array and use that new DOM tree to populate a DOM tree for each movie that is in the data.entries array render a new DOM tree based on the information stored in the data.entries object 

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
