### ISSUE TITLE
Feature #5: User can Remove a movie from their movies list they want to watch list

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/WatchList#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an movie/show from their My List page 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click a button that will ask a follow up prompt if they really want to delete the movie they are looking at. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="381" alt="Screen Shot 2023-03-05 at 8 10 26 PM" src="https://user-images.githubusercontent.com/117954421/223017748-7a3edc94-07ce-4876-a8f1-c1a77f31ac5e.png">

<img width="212" alt="Screen Shot 2023-03-05 at 8 10 52 PM" src="https://user-images.githubusercontent.com/117954421/223017771-00d74d53-19f1-461d-8df2-349158f24920.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a class to the section my list page called section-on to toggle for when the page needs to show the modal
- [x] Apply CSS to the modal pop up 
     - [x] Mobile
     - [x] Desktop
- [x] Add a delete button to the DOM tree that renders the MY LIST page 
- [x] Show a confirmation model when the user clicks on the delete button 
     - [x] If the user clicks cancel hide the modal 
- [x] IF the user clicks the delete button and clicks confirm
     - [x] remove the object from the data.entries array
     - [x] remove the entry's li from the DOM 
     - [x] hide the modal for both confirm and cancel 
 - [x] Add data.view to functions to keep current view on that page when refreshing
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
